LoadFont('number','THlib\\font\\number.fnt',true)
SetFontState2('number',nil,nil,0.75,nil)
LoadFont('item','THlib\\font\\item.fnt',true)
LoadFont('menu','THlib\\font\\menu.fnt',true)
LoadFont('bonus','THlib\\font\\bonus.fnt',false)